poc_dbt:
  outputs:
    dev:
      dataset: dbt_poc_bch
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /secrets/dbt-user-creds.json
      location: US
      method: service-account
      priority: interactive
      project: poc-bco-chile
      threads: 1
      type: bigquery
  target: dev